#!/usr/bin/env python3
"""Generate Pac-Man's sprites as pixel art.

Why not just fillCircle + a black wedge, as this used to do: at a 9 px sprite
the rasteriser makes all the decisions. Garmin renders fillCircle(r=4) as an
8 px diameter, so the body came out 9 wide by 8 tall and the back tapered to a
3 px point -- visibly chopped. Drawing explicit pixels removes the guesswork
and makes the shape editable by hand, the same as the sensor icons.

  python3 tools/gen_sprite_art.py     # prints them, writes tools/sprites.py
"""
S = 9                     # sprite is exactly one cell across
SS = 4                    # supersample per pixel
R = 4.35                  # body radius, tuned for symmetric 3,5,7,9,9,9,7,5,3 rows
C = S / 2.0                # sprite centre: pixel centres sit at x + 0.5
import math

# Mouth half-angles for the three animation phases, facing RIGHT.
PHASES = [0.0, 0.40, 0.80]
# The death animation opens from nothing to gone, facing up.
DEATH = [0.35, 0.70, 1.05, 1.40, 1.75, 2.10, 2.50, 2.95]


def render(half, facing):
    art = []
    for y in range(S):
        row = ""
        for x in range(S):
            hits = 0
            for sy in range(SS):
                for sx in range(SS):
                    px = x + (sx + 0.5) / SS - C
                    py = y + (sy + 0.5) / SS - C
                    if px * px + py * py > R * R:
                        continue
                    if half > 0.001:
                        d = math.atan2(py, px) - facing
                        while d > math.pi:
                            d -= 2 * math.pi
                        while d < -math.pi:
                            d += 2 * math.pi
                        if abs(d) <= half:
                            continue          # inside the mouth
                    hits += 1
            row += "#" if hits * 2 >= SS * SS else "."
        art.append(row)
    return art


def rot90(art):
    """Rotate clockwise, so RIGHT-facing art can make the other three."""
    return ["".join(art[S - 1 - x][y] for x in range(S)) for y in range(S)]


if __name__ == "__main__":
    body = render(0.0, 0.0)
    print("body rows:", [r.count("#") for r in body])
    for label, half in zip(("shut", "half", "wide"), PHASES):
        print("\n%s (facing RIGHT)" % label)
        for r in render(half, 0.0):
            print("   " + r.replace(".", " ").replace("#", "█"))

    with open("tools/sprites.py", "w") as f:
        f.write('"""GENERATED by tools/gen_sprite_art.py -- but safe to hand-edit.\n\n'
                'Pac-Man at exactly one cell across. Only the RIGHT-facing phases are\n'
                'stored; the other three directions are rotations, produced at bake\n'
                'time by gen_sprites_mc.py. Every row must be S characters.\n"""\n\n')
        f.write("S = %d\n\n" % S)
        f.write("# mouth shut, half open, wide open -- facing RIGHT\n")
        f.write("PHASES = [\n")
        for half in PHASES:
            f.write("    [\n")
            for r in render(half, 0.0):
                f.write('        "%s",\n' % r)
            f.write("    ],\n")
        f.write("]\n\n# the death animation: opens upward until nothing is left\n")
        f.write("DEATH = [\n")
        for half in DEATH:
            f.write("    [\n")
            for r in render(half, -math.pi / 2):
                f.write('        "%s",\n' % r)
            f.write("    ],\n")
        f.write("]\n\n")
        f.write('''
def rot90(art):
    """Rotate clockwise: RIGHT-facing art makes the other three directions."""
    return ["".join(art[S - 1 - x][y] for x in range(S)) for y in range(S)]


def runs(art):
    """Merge each row's lit pixels into horizontal runs: (row, x0, x1)."""
    out = []
    for y, row in enumerate(art):
        x = 0
        while x < S:
            if row[x] == "#":
                x0 = x
                while x < S and row[x] == "#":
                    x += 1
                out.append((y, x0, x - 1))
            else:
                x += 1
    return out


def selftest():
    for name, group in (("PHASES", PHASES), ("DEATH", DEATH)):
        for i, art in enumerate(group):
            assert len(art) == S, "%s[%d] has %d rows" % (name, i, len(art))
            for y, r in enumerate(art):
                assert len(r) == S, "%s[%d] row %d is %d wide" % (name, i, y, len(r))
    return True
''')
    print("\nwrote tools/sprites.py")
