#!/usr/bin/env python3
"""Bake tools/maze.py into source/MazeData.mc as per-row 28-bit masks.

Bit c of row r is tile (c, r).  Keeps string slicing out of the hot loop:
a wall test becomes ((wall[r] >> c) & 1).
"""
import maze as M

info = M.validate()
if info["orphans"]:
    raise SystemExit("maze has unreachable tiles: %r" % info["orphans"])


def mask(pred):
    out = []
    for r in range(M.ROWS):
        m = 0
        for c in range(M.COLS):
            if pred(M.MAZE[r][c]):
                m |= 1 << c
        out.append(m)
    return out


wall  = mask(lambda ch: ch == "#")
door  = mask(lambda ch: ch == "-")
dot   = mask(lambda ch: ch == ".")
power = mask(lambda ch: ch == "o")

# "Void" = the black margin either side of the tunnel rows. Not playfield,
# not wall: nothing may enter it and nothing is drawn there.
void = mask(lambda ch: False)
for r in range(9, 20):
    if r == 14:          # the wrap tunnel: corridor all the way out
        continue
    m = 0
    for c in range(M.COLS):
        if M.MAZE[r][c] == " " and (c < 6 or c > 21):
            m |= 1 << c
    void[r] = m


def arr(name, vals):
    body = ",\n        ".join(", ".join("0x%07X" % v for v in vals[i:i + 4])
                              for i in range(0, len(vals), 4))
    return ("    const %s = [\n        %s\n    ] as Array<Number>;\n" % (name, body))


with open("source/MazeData.mc", "w") as f:
    f.write("""// GENERATED by tools/gen_maze_mc.py -- do not edit by hand.
// The authentic 28x31 Pac-Man playfield, one 28-bit mask per row.
// Bit c of row r is tile (c, r).  %d dots + %d power pellets = %d, which is
// exactly the arcade's count.
import Toybox.Lang;

module MazeData {
    const COLS = %d;
    const ROWS = %d;
    const DOT_TOTAL = %d;

""" % (info["dots"], info["power"], info["dots"] + info["power"],
       M.COLS, M.ROWS, info["dots"] + info["power"]))
    f.write(arr("WALL", wall))
    f.write("\n")
    f.write(arr("DOOR", door))
    f.write("\n")
    f.write(arr("DOT", dot))
    f.write("\n")
    f.write(arr("POWER", power))
    f.write("\n")
    f.write(arr("VOID", void))
    f.write("\n")
    # Pre-OR'd blocking masks. The BFS inner loop is the hottest code in the
    # app; this turns "can I step here" into one array read and one shift.
    f.write("    // Blocked-for-ghosts and blocked-for-Pac-Man, pre-combined.\n")
    f.write(arr("BLOCK_G", [wall[r] | void[r] for r in range(M.ROWS)]))
    f.write("\n")
    f.write(arr("BLOCK_P", [wall[r] | void[r] | door[r] for r in range(M.ROWS)]))
    f.write("}\n")

print("wrote source/MazeData.mc  (%d dots + %d pellets)"
      % (info["dots"], info["power"]))

# ---------------------------------------------------------------------------
# Wall outlines: runs with corner-aware ends, plus the convex corners.
#
# See maze.wall_runs() for why the run ends carry an inset sign. The corners
# are grid points with exactly one solid tile around them; each becomes a
# short diagonal that chamfers the join. At a 1 px stroke a rounded corner
# has no room to be a real arc -- it IS a chamfer -- and drawing it as one
# line rasterises predictably instead of leaving stray pixels, which is what
# dc.drawArc gave us.

SEG = M.wall_runs()


def convex_corners():
    out = []
    for r in range(M.ROWS + 1):
        for c in range(M.COLS + 1):
            q = [M._solid(c - 1, r - 1), M._solid(c, r - 1),
                 M._solid(c - 1, r), M._solid(c, r)]
            if sum(q) != 1:
                continue
            i = q.index(True)
            sx = -1 if i in (0, 2) else 1
            sy = -1 if i in (0, 1) else 1
            out.append((c, r, sx, sy))
    return out


COR = convex_corners()

with open("source/MazeData.mc", "a") as f:
    f.write("\n// Wall outlines: %d runs (from %d raw tile edges) + %d convex\n"
            "// corners. Run ends carry the sign of the inset to apply, so two\n"
            "// runs meeting at a corner land on the same point instead of\n"
            "// overshooting and crossing in a little plus sign.\n"
            % (len(SEG), 732, len(COR)))
    f.write("module MazeWalls {\n    const N = %d;\n" % len(SEG))
    flat = [v for t in SEG for v in t]
    body = ",\n        ".join(", ".join("%d" % v for v in flat[i:i + 18])
                              for i in range(0, len(flat), 18))
    f.write("    // groups of 6: type, a, b, fixed, startInsetSign, endInsetSign\n")
    f.write("    const SEG = [\n        %s\n    ] as Array<Number>;\n\n" % body)
    f.write("    const CORNER_N = %d;\n" % len(COR))
    cflat = [v for t in COR for v in t]
    cbody = ",\n        ".join(", ".join("%d" % v for v in cflat[i:i + 20])
                               for i in range(0, len(cflat), 20))
    f.write("    // groups of 4: gridCol, gridRow, xSign, ySign\n")
    f.write("    const CORNER = [\n        %s\n    ] as Array<Number>;\n}\n" % cbody)

print("wall runs: %d  convex corners: %d" % (len(SEG), len(COR)))
