#!/usr/bin/env python3
"""Bake tools/tempest_levels.py into source/TempestData.mc.

Each shape is normalised by its longest *radius*, not its longest coordinate:
the square's corner sits at 1244 from the centre when its sides are at 880, so
normalising on coordinates alone would push it off a round screen.
"""
import math
import tempest_levels as T

T.selftest()

offs, counts, closed, xs, ys = [], [], [], [], []
for name, pts, cl in T.LEVELS:
    m = max(math.hypot(x, y) for x, y in pts)
    k = 1000.0 / m
    offs.append(len(xs))
    counts.append(T.segments(pts, cl))
    closed.append(1 if cl else 0)
    for x, y in pts:
        xs.append(int(round(x * k)))
        ys.append(int(round(y * k)))
    print("  %-9s %2d pts, %2d seg, %-6s  longest radius %4d -> 1000"
          % (name, len(pts), T.segments(pts, cl),
             "closed" if cl else "OPEN", int(m)))


def arr(name, vals, per=12):
    body = ",\n        ".join(", ".join(str(v) for v in vals[i:i + per])
                              for i in range(0, len(vals), per))
    return "    const %s = [\n        %s\n    ] as Array<Number>;\n" % (name, body)


with open("source/TempestData.mc", "w") as f:
    f.write("""// GENERATED by tools/gen_tempest_mc.py from tools/tempest_levels.py --
// edit the shapes there, not here.
//
// A level is its rim. The far end of the tube is the same outline shrunk
// toward the centre, so the rim alone decides what the level looks like: a
// circle, a square, a plus, a pinwheel, or an open trough with walls at each
// end that you cannot wrap around.
//
// Points are normalised so the furthest one sits 1000 from the centre, which
// is what keeps every shape inside a round bezel. Segment counts differ per
// level because corners are kept rather than resampled away.
import Toybox.Lang;

module TempestData {
    const LEVELS = %d;

""" % len(T.LEVELS))
    f.write(arr("OFF", offs))
    f.write("\n")
    f.write(arr("NSEG", counts))
    f.write("\n    // 1 = the rim wraps, 0 = it has ends\n")
    f.write(arr("CLOSED", closed))
    f.write("\n")
    f.write(arr("PX", xs))
    f.write("\n")
    f.write(arr("PY", ys))
    f.write("}\n")

print("wrote source/TempestData.mc  (%d levels, %d points)" % (len(T.LEVELS), len(xs)))
