#!/usr/bin/env python3
"""Bake tools/pixfont.py into Connect IQ BMFont resources.

Integer scaling only -- every font pixel becomes an N x N square, which is
what keeps it looking like an arcade and not like shrunken text.  Glyphs
are white with hard 0/255 alpha so `dc.setColor` tints them at runtime.

  python3 tools/gen_fonts.py
"""
from PIL import Image
import pixfont as F

OUT = "resources/fonts"
DIGITS = "0123456789: "
SMALLNUM = "0123456789-"
FULL = "".join(F.CHARS)

# (basename, scale, charset)  -- big only ever renders a clock, so it only
# needs digits; that keeps the atlas small in the .prg.
FONTS = [
    ("pac_tiny",  2, SMALLNUM),
    ("pac_small", 3, FULL),
    ("pac_score", 4, FULL),
    ("pac_big",   7, DIGITS),
]


def gen(base, scale, chars):
    chars = sorted(set(chars))
    cw, ch = F.GW * scale, F.GH * scale
    img = Image.new("RGBA", (cw * len(chars), ch), (255, 255, 255, 0))
    px = img.load()

    recs = []
    for i, c in enumerate(chars):
        ox = i * cw
        g = F.glyph(c)
        for ry in range(F.GH):
            row = g[ry]
            for rx in range(F.GW):
                if row[rx] == "#":
                    for dy in range(scale):
                        for dx in range(scale):
                            px[ox + rx * scale + dx, ry * scale + dy] = (255, 255, 255, 255)
        # One font-pixel of tracking, scaled, so glyphs never touch.
        recs.append((ord(c), ox, cw, (F.advance(c) + 1) * scale))

    img.save("%s/%s.png" % (OUT, base))
    with open("%s/%s.fnt" % (OUT, base), "w") as f:
        f.write('info face="PacPixel" size=%d bold=0 italic=0 charset="" '
                'unicode=1 stretchH=100 smooth=0 aa=1 padding=0,0,0,0 '
                'spacing=0,0\n' % ch)
        f.write('common lineHeight=%d base=%d scaleW=%d scaleH=%d pages=1 '
                'packed=0\n' % (ch, ch, img.width, ch))
        f.write('page id=0 file="%s.png"\n' % base)
        f.write('chars count=%d\n' % len(recs))
        for cid, x, w, xa in recs:
            f.write('char id=%d x=%d y=0 width=%d height=%d xoffset=0 '
                    'yoffset=0 xadvance=%d page=0 chnl=15\n'
                    % (cid, x, w, ch, xa))
        f.write('kernings count=0\n')
    print("  %-10s scale=%d  glyph=%dx%d  %2d chars  atlas=%dx%d"
          % (base, scale, cw, ch, len(chars), img.width, ch))
    return base


ids = {"pac_tiny": "FontTiny", "pac_small": "FontSmall",
       "pac_score": "FontScore", "pac_big": "FontBig"}
for base, scale, chars in FONTS:
    gen(base, scale, chars)

with open("%s/fonts.xml" % OUT, "w") as f:
    f.write("<!-- GENERATED by tools/gen_fonts.py -->\n<resources>\n    <fonts>\n")
    for base, _, _ in FONTS:
        f.write('        <font id="%s" filename="%s.fnt" antialias="false"/>\n'
                % (ids[base], base))
    f.write("    </fonts>\n</resources>\n")
print("wrote %s/fonts.xml" % OUT)
