#!/usr/bin/env python3
"""Bake tools/invaders.py into source/InvaderData.mc as horizontal runs.

Index is rank * 2 + animation frame, ranks running top to bottom, so the game
can look a sprite up straight from the row it is drawing.
"""
import invaders as I

I.selftest()

sprites = []
for frames in I.RANKS:
    sprites.append(frames[0])
    sprites.append(frames[1])

runs, off, cnt = [], [], []
for art in sprites:
    r = I.runs(art)
    off.append(len(runs))
    cnt.append(len(r))
    runs.extend(r)
flat = [v for t in runs for v in t]


def arr(name, vals, per):
    body = ",\n        ".join(", ".join(str(v) for v in vals[i:i + per])
                              for i in range(0, len(vals), per))
    return "    const %s = [\n        %s\n    ] as Array<Number>;\n" % (name, body)


with open("source/InvaderData.mc", "w") as f:
    f.write("""// GENERATED by tools/gen_invaders_mc.py from tools/invaders.py -- edit the
// art there, not here.
//
// Five ranks x two animation frames, %dx%d, drawn at 2x. Index is
// rank * 2 + frame. Worst sprite is %d runs, so a full formation of 55 costs
// about %d draw calls against the ~700-call watchdog.
import Toybox.Lang;

module InvaderData {
    const W = %d;
    const H = %d;
    const SCALE = 2;

""" % (I.W, I.H, max(cnt), max(cnt) * 55, I.W, I.H))
    f.write(arr("OFF", off, 10))
    f.write("\n")
    f.write(arr("CNT", cnt, 10))
    f.write("\n    // groups of 3: row, x0, x1\n")
    f.write(arr("RUNS", flat, 15))
    f.write("}\n")

print("wrote source/InvaderData.mc  %d sprites, worst %d runs" % (len(sprites), max(cnt)))
