#!/usr/bin/env python3
"""Bake tools/icons.py into source/IconData.mc as horizontal runs.

The icons are static, so they get painted into the maze buffer once and cost
nothing per frame; only the number inside them is drawn live. Runs rather
than per-pixel rectangles keep even that one-off paint cheap.

Heights are per-icon -- the heart and the bust are not the same shape and
there is no reason to pad one to match the other; each is centred on its own.
"""
import icons as I

I.selftest()


def emit(f, name, art, rows):
    r = I.runs(art)
    flat = [v for t in r for v in t]
    body = ",\n        ".join(", ".join(str(v) for v in flat[i:i + 15])
                              for i in range(0, len(flat), 15))
    f.write("    // %d rows, %d runs; groups of 3: row, x0, x1\n" % (len(art), len(r)))
    f.write("    const %s_H = %d;\n" % (name, len(art)))
    f.write("    const %s_N = %d;\n" % (name, len(r)))
    f.write("    const %s = [\n        %s\n    ] as Array<Number>;\n" % (name, body))
    f.write("    const %s_TEXT_TOP = %d;\n" % (name, rows[0]))
    f.write("    const %s_TEXT_BOT = %d;\n\n" % (name, rows[1]))


with open("source/IconData.mc", "w") as f:
    f.write("""// GENERATED by tools/gen_icons_mc.py from tools/icons.py -- edit the art
// there, not here.
// Filled pixel icons for the sensor read-outs, as horizontal runs.
import Toybox.Lang;

module IconData {
    const W = %d;

""" % I.W)
    emit(f, "HEART", I.HEART, I.HEART_TEXT_ROWS)
    emit(f, "BODY", I.BODY, I.BODY_TEXT_ROWS)
    f.write("}\n")

print("wrote source/IconData.mc  heart %dx%d (%d runs), body %dx%d (%d runs)"
      % (I.W, len(I.HEART), len(I.runs(I.HEART)),
         I.W, len(I.BODY), len(I.runs(I.BODY))))
