#!/usr/bin/env python3
"""Bake tools/sprites.py into source/SpriteData.mc as horizontal runs.

Only the RIGHT-facing art is stored; the other three directions are rotations
generated here, so there is one shape to hand-edit rather than four to keep in
agreement.

Index order matches Maze.UP/LEFT/DOWN/RIGHT = 0/1/2/3, so the view can look a
sprite up with dir * 3 + mouthPhase. The death frames follow at index 12.
"""
import sprites as SP

SP.selftest()

# Base art faces RIGHT; each clockwise rotation moves the mouth right -> down.
by_dir = {3: SP.PHASES}
by_dir[2] = [SP.rot90(a) for a in SP.PHASES]
by_dir[1] = [SP.rot90(SP.rot90(a)) for a in SP.PHASES]
by_dir[0] = [SP.rot90(SP.rot90(SP.rot90(a))) for a in SP.PHASES]

sprites = []
for d in (0, 1, 2, 3):
    sprites.extend(by_dir[d])
sprites.extend(SP.DEATH)

runs, off, cnt = [], [], []
for art in sprites:
    r = SP.runs(art)
    off.append(len(runs))
    cnt.append(len(r))
    runs.extend(r)

flat = [v for t in runs for v in t]


def arr(name, vals, per):
    body = ",\n        ".join(", ".join(str(v) for v in vals[i:i + per])
                              for i in range(0, len(vals), per))
    return "    const %s = [\n        %s\n    ] as Array<Number>;\n" % (name, body)


with open("source/SpriteData.mc", "w") as f:
    f.write("""// GENERATED by tools/gen_sprites_mc.py from tools/sprites.py -- edit the
// art there, not here.
//
// Pac-Man as explicit pixels rather than fillCircle plus a black wedge. At a
// %d px sprite the rasteriser was making the decisions: Garmin draws
// fillCircle(r=4) as an 8 px diameter, so the body came out 9 wide by 8 tall
// and the back tapered to a 3 px point. These rows are symmetric by
// construction.
//
// Look-up is dir * PHASES + mouthPhase, with dir matching Maze.UP/LEFT/DOWN/
// RIGHT = 0/1/2/3. The %d death frames start at DEATH_FIRST.
import Toybox.Lang;

module SpriteData {
    const S = %d;
    const PHASES = %d;
    const DEATH_FIRST = %d;
    const DEATH_COUNT = %d;

""" % (SP.S, len(SP.DEATH), SP.S, len(SP.PHASES), 12, len(SP.DEATH)))
    f.write("    // start index into RUNS for each sprite\n")
    f.write(arr("OFF", off, 10))
    f.write("\n    // how many runs each sprite has\n")
    f.write(arr("CNT", cnt, 10))
    f.write("\n    // groups of 3: row, x0, x1\n")
    f.write(arr("RUNS", flat, 15))
    f.write("}\n")

print("wrote source/SpriteData.mc  %d sprites, %d runs (avg %.1f per sprite)"
      % (len(sprites), len(runs), len(runs) / float(len(sprites))))
