"""GENERATED by tools/gen_sprite_art.py -- but safe to hand-edit.

Pac-Man at exactly one cell across. Only the RIGHT-facing phases are
stored; the other three directions are rotations, produced at bake
time by gen_sprites_mc.py. Every row must be S characters.
"""

S = 9

# mouth shut, half open, wide open -- facing RIGHT
PHASES = [
    [
        "...###...",
        ".#######.",
        ".#######.",
        "#########",
        "#########",
        "#########",
        ".#######.",
        ".#######.",
        "...###...",
    ],
    [
        "...###...",
        ".#######.",
        ".#######.",
        "#######..",
        "#####....",
        "#######..",
        ".#######.",
        ".#######.",
        "...###...",
    ],
    [
        "...###...",
        ".######..",
        ".#####...",
        "#####....",
        "#####....",
        "#####....",
        ".#####...",
        ".######..",
        "...###...",
    ],
]

# the death animation: opens upward until nothing is left
DEATH = [
    [
        ".........",
        ".##...##.",
        ".###.###.",
        "####.####",
        "#########",
        "#########",
        ".#######.",
        ".#######.",
        "...###...",
    ],
    [
        ".........",
        ".#.....#.",
        ".##...##.",
        "####.####",
        "#########",
        "#########",
        ".#######.",
        ".#######.",
        "...###...",
    ],
    [
        ".........",
        ".........",
        ".........",
        "###...###",
        "#########",
        "#########",
        ".#######.",
        ".#######.",
        "...###...",
    ],
    [
        ".........",
        ".........",
        ".........",
        ".........",
        "#########",
        "#########",
        ".#######.",
        ".#######.",
        "...###...",
    ],
    [
        ".........",
        ".........",
        ".........",
        ".........",
        "....#....",
        "#########",
        ".#######.",
        ".#######.",
        "...###...",
    ],
    [
        ".........",
        ".........",
        ".........",
        ".........",
        ".........",
        "...###...",
        ".#######.",
        ".#######.",
        "...###...",
    ],
    [
        ".........",
        ".........",
        ".........",
        ".........",
        ".........",
        "....#....",
        "...###...",
        "..#####..",
        "...###...",
    ],
    [
        ".........",
        ".........",
        ".........",
        ".........",
        ".........",
        ".........",
        "....#....",
        "....#....",
        "....#....",
    ],
]


def rot90(art):
    """Rotate clockwise: RIGHT-facing art makes the other three directions."""
    return ["".join(art[S - 1 - x][y] for x in range(S)) for y in range(S)]


def runs(art):
    """Merge each row's lit pixels into horizontal runs: (row, x0, x1)."""
    out = []
    for y, row in enumerate(art):
        x = 0
        while x < S:
            if row[x] == "#":
                x0 = x
                while x < S and row[x] == "#":
                    x += 1
                out.append((y, x0, x - 1))
            else:
                x += 1
    return out


def selftest():
    for name, group in (("PHASES", PHASES), ("DEATH", DEATH)):
        for i, art in enumerate(group):
            assert len(art) == S, "%s[%d] has %d rows" % (name, i, len(art))
            for y, r in enumerate(art):
                assert len(r) == S, "%s[%d] row %d is %d wide" % (name, i, y, len(r))
    return True
