// GENERATED by tools/gen_icons_mc.py from tools/icons.py -- edit the art
// there, not here.
// Filled pixel icons for the sensor read-outs, as horizontal runs.
import Toybox.Lang;

module IconData {
    const W = 15;

    // 12 rows, 15 runs; groups of 3: row, x0, x1
    const HEART_H = 12;
    const HEART_N = 15;
    const HEART = [
        0, 2, 4, 0, 10, 12, 1, 1, 5, 1, 9, 13, 2, 0, 6,
        2, 8, 14, 3, 0, 14, 4, 0, 14, 5, 1, 13, 6, 2, 12,
        7, 3, 11, 8, 4, 10, 9, 5, 9, 10, 6, 8, 11, 7, 7
    ] as Array<Number>;
    const HEART_TEXT_TOP = 3;
    const HEART_TEXT_BOT = 6;

    // 16 rows, 16 runs; groups of 3: row, x0, x1
    const BODY_H = 16;
    const BODY_N = 16;
    const BODY = [
        0, 6, 8, 1, 5, 9, 2, 4, 10, 3, 4, 10, 4, 4, 10,
        5, 5, 9, 6, 6, 8, 7, 5, 9, 8, 4, 10, 9, 3, 11,
        10, 2, 12, 11, 1, 13, 12, 1, 13, 13, 1, 13, 14, 1, 13,
        15, 1, 13
    ] as Array<Number>;
    const BODY_TEXT_TOP = 11;
    const BODY_TEXT_BOT = 14;

}
