// GENERATED by tools/gen_invaders_mc.py from tools/invaders.py -- edit the
// art there, not here.
//
// Five ranks x two animation frames, 6x5, drawn at 2x. Index is
// rank * 2 + frame. Worst sprite is 9 runs, so a full formation of 55 costs
// about 495 draw calls against the ~700-call watchdog.
import Toybox.Lang;

module InvaderData {
    const W = 6;
    const H = 5;
    const SCALE = 2;

    const OFF = [
        0, 9, 18, 27, 35, 44, 52, 61, 69, 78
    ] as Array<Number>;

    const CNT = [
        9, 9, 9, 8, 9, 8, 9, 8, 9, 8
    ] as Array<Number>;

    // groups of 3: row, x0, x1
    const RUNS = [
        0, 1, 4, 1, 0, 5, 2, 0, 1, 2, 4, 5, 3, 1, 1,
        3, 4, 4, 4, 0, 0, 4, 2, 3, 4, 5, 5, 0, 1, 4,
        1, 0, 5, 2, 0, 1, 2, 4, 5, 3, 0, 0, 3, 2, 3,
        3, 5, 5, 4, 1, 1, 4, 4, 4, 0, 0, 0, 0, 5, 5,
        1, 1, 4, 2, 0, 1, 2, 4, 5, 3, 0, 5, 4, 0, 0,
        4, 2, 3, 4, 5, 5, 0, 0, 0, 0, 5, 5, 1, 0, 4,
        2, 0, 1, 2, 4, 5, 3, 0, 5, 4, 1, 1, 4, 4, 4,
        0, 0, 0, 0, 5, 5, 1, 1, 4, 2, 0, 1, 2, 4, 5,
        3, 0, 5, 4, 0, 0, 4, 2, 3, 4, 5, 5, 0, 0, 0,
        0, 5, 5, 1, 0, 4, 2, 0, 1, 2, 4, 5, 3, 0, 5,
        4, 1, 1, 4, 4, 4, 0, 1, 4, 1, 0, 5, 2, 0, 0,
        2, 2, 3, 2, 5, 5, 3, 1, 4, 4, 0, 0, 4, 2, 3,
        4, 5, 5, 0, 1, 4, 1, 0, 5, 2, 0, 0, 2, 2, 3,
        2, 5, 5, 3, 1, 4, 4, 1, 1, 4, 4, 4, 0, 1, 4,
        1, 0, 5, 2, 0, 0, 2, 2, 3, 2, 5, 5, 3, 1, 4,
        4, 0, 0, 4, 2, 3, 4, 5, 5, 0, 1, 4, 1, 0, 5,
        2, 0, 0, 2, 2, 3, 2, 5, 5, 3, 1, 4, 4, 1, 1,
        4, 4, 4
    ] as Array<Number>;
}
