// GENERATED by tools/gen_sprites_mc.py from tools/sprites.py -- edit the
// art there, not here.
//
// Pac-Man as explicit pixels rather than fillCircle plus a black wedge. At a
// 9 px sprite the rasteriser was making the decisions: Garmin draws
// fillCircle(r=4) as an 8 px diameter, so the body came out 9 wide by 8 tall
// and the back tapered to a 3 px point. These rows are symmetric by
// construction.
//
// Look-up is dir * PHASES + mouthPhase, with dir matching Maze.UP/LEFT/DOWN/
// RIGHT = 0/1/2/3. The 8 death frames start at DEATH_FIRST.
import Toybox.Lang;

module SpriteData {
    const S = 9;
    const PHASES = 3;
    const DEATH_FIRST = 12;
    const DEATH_COUNT = 8;

    // start index into RUNS for each sprite
    const OFF = [
        0, 9, 20, 29, 38, 47, 56, 65, 76, 85,
        94, 103, 112, 123, 134, 141, 146, 151, 155, 159
    ] as Array<Number>;

    // how many runs each sprite has
    const CNT = [
        9, 11, 9, 9, 9, 9, 9, 11, 9, 9,
        9, 9, 11, 11, 7, 5, 5, 4, 4, 3
    ] as Array<Number>;

    // groups of 3: row, x0, x1
    const RUNS = [
        0, 3, 5, 1, 1, 7, 2, 1, 7, 3, 0, 8, 4, 0, 8,
        5, 0, 8, 6, 1, 7, 7, 1, 7, 8, 3, 5, 1, 1, 2,
        1, 6, 7, 2, 1, 3, 2, 5, 7, 3, 0, 3, 3, 5, 8,
        4, 0, 8, 5, 0, 8, 6, 1, 7, 7, 1, 7, 8, 3, 5,
        2, 1, 1, 2, 7, 7, 3, 0, 2, 3, 6, 8, 4, 0, 8,
        5, 0, 8, 6, 1, 7, 7, 1, 7, 8, 3, 5, 0, 3, 5,
        1, 1, 7, 2, 1, 7, 3, 0, 8, 4, 0, 8, 5, 0, 8,
        6, 1, 7, 7, 1, 7, 8, 3, 5, 0, 3, 5, 1, 1, 7,
        2, 1, 7, 3, 2, 8, 4, 4, 8, 5, 2, 8, 6, 1, 7,
        7, 1, 7, 8, 3, 5, 0, 3, 5, 1, 2, 7, 2, 3, 7,
        3, 4, 8, 4, 4, 8, 5, 4, 8, 6, 3, 7, 7, 2, 7,
        8, 3, 5, 0, 3, 5, 1, 1, 7, 2, 1, 7, 3, 0, 8,
        4, 0, 8, 5, 0, 8, 6, 1, 7, 7, 1, 7, 8, 3, 5,
        0, 3, 5, 1, 1, 7, 2, 1, 7, 3, 0, 8, 4, 0, 8,
        5, 0, 3, 5, 5, 8, 6, 1, 3, 6, 5, 7, 7, 1, 2,
        7, 6, 7, 0, 3, 5, 1, 1, 7, 2, 1, 7, 3, 0, 8,
        4, 0, 8, 5, 0, 2, 5, 6, 8, 6, 1, 1, 6, 7, 7,
        0, 3, 5, 1, 1, 7, 2, 1, 7, 3, 0, 8, 4, 0, 8,
        5, 0, 8, 6, 1, 7, 7, 1, 7, 8, 3, 5, 0, 3, 5,
        1, 1, 7, 2, 1, 7, 3, 0, 6, 4, 0, 4, 5, 0, 6,
        6, 1, 7, 7, 1, 7, 8, 3, 5, 0, 3, 5, 1, 1, 6,
        2, 1, 5, 3, 0, 4, 4, 0, 4, 5, 0, 4, 6, 1, 5,
        7, 1, 6, 8, 3, 5, 1, 1, 2, 1, 6, 7, 2, 1, 3,
        2, 5, 7, 3, 0, 3, 3, 5, 8, 4, 0, 8, 5, 0, 8,
        6, 1, 7, 7, 1, 7, 8, 3, 5, 1, 1, 1, 1, 7, 7,
        2, 1, 2, 2, 6, 7, 3, 0, 3, 3, 5, 8, 4, 0, 8,
        5, 0, 8, 6, 1, 7, 7, 1, 7, 8, 3, 5, 3, 0, 2,
        3, 6, 8, 4, 0, 8, 5, 0, 8, 6, 1, 7, 7, 1, 7,
        8, 3, 5, 4, 0, 8, 5, 0, 8, 6, 1, 7, 7, 1, 7,
        8, 3, 5, 4, 4, 4, 5, 0, 8, 6, 1, 7, 7, 1, 7,
        8, 3, 5, 5, 3, 5, 6, 1, 7, 7, 1, 7, 8, 3, 5,
        5, 4, 4, 6, 3, 5, 7, 2, 6, 8, 3, 5, 6, 4, 4,
        7, 4, 4, 8, 4, 4
    ] as Array<Number>;
}
