// GENERATED by tools/gen_tempest_mc.py from tools/tempest_levels.py --
// edit the shapes there, not here.
//
// A level is its rim. The far end of the tube is the same outline shrunk
// toward the centre, so the rim alone decides what the level looks like: a
// circle, a square, a plus, a pinwheel, or an open trough with walls at each
// end that you cannot wrap around.
//
// Points are normalised so the furthest one sits 1000 from the centre, which
// is what keeps every shape inside a round bezel. Segment counts differ per
// level because corners are kept rather than resampled away.
import Toybox.Lang;

module TempestData {
    const LEVELS = 5;

    const OFF = [
        0, 16, 32, 44, 60
    ] as Array<Number>;

    const NSEG = [
        16, 16, 12, 16, 12
    ] as Array<Number>;

    // 1 = the rim wraps, 0 = it has ends
    const CLOSED = [
        1, 1, 1, 1, 0
    ] as Array<Number>;

    const PX = [
        0, 383, 707, 924, 1000, 924, 707, 383, 0, -383, -707, -924,
        -1000, -924, -707, -383, -707, -354, 0, 354, 707, 707, 707, 707,
        707, 354, 0, -354, -707, -707, -707, -707, -319, 319, 319, 948,
        948, 319, 319, -319, -319, -948, -948, -319, 0, 161, 707, 388,
        1000, 388, 707, 161, 0, -161, -707, -388, -1000, -388, -707, -161,
        -806, -689, -572, -455, -338, -169, 0, 169, 338, 455, 572, 689,
        806
    ] as Array<Number>;

    const PY = [
        -1000, -924, -707, -383, 0, 383, 707, 924, 1000, 924, 707, 383,
        0, -383, -707, -924, -707, -707, -707, -707, -707, -354, 0, 354,
        707, 707, 707, 707, 707, 354, 0, -354, -948, -948, -319, -319,
        319, 319, 948, 948, 319, 319, -319, -319, -1000, -388, -707, -161,
        0, 161, 707, 388, 1000, 388, 707, 161, 0, -161, -707, -388,
        -592, -296, 0, 296, 592, 592, 592, 592, 592, 296, 0, -296,
        -592
    ] as Array<Number>;
}
